### Задание 1

In [ ]:
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [4]:
N = int(input('Введите число: '))
y = []
for i in range(N):
    y.append(i)
y.reverse()
answer = np.array(y)
answer

Введите число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

In [5]:
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [18]:
# N = int(input('Введите число: '))
N = 10
data = np.diag(np.arange(N, 0, -1))
data

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [19]:
sum_diagonal = 0
index = 0
for row in data:
    sum_diagonal += row[index]
    index += 1
print(sum_diagonal)

55


### Задание 3

In [21]:
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [27]:
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

In [ ]:
# Имеется матрица покупок в интернет-магазине.
# Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [28]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [30]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
# Найдите самого похожего пользователя.
# Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [31]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [41]:
result = []
for row in users_stats:
    result.append(cosine(row, next_user_stats))
result

[0.19999999999999996,
 0.8451542547285165,
 0.3999999999999999,
 0.7905694150420948,
 0.3999999999999999,
 0.0,
 0.0,
 0.9486832980505138,
 0.0,
 0.0]